name: Android CI - Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate Gradle wrapper if missing
        run: |
          if [ ! -f ./gradlew ]; then
            echo "gradlew not found - generating wrapper"
            ./gradlew wrapper || true
          fi

      - name: Grant Gradlew permission
        run: if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Rupeedesk7-debug-apk
          path: app/build/outputs/apk/debug/*.apk
